language: julia
os:
  - osx
  - linux
  - windows
arch:
  - x64
  - x86
julia:
  - 1.0
  - 1.1
  - nightly
env:
  - PYTHON=""
jobs:
  allow_failures:
    - julia: nightly

  # Test 32-bit only on Linux
  exclude:
    - os: osx
      arch: x86
    - os: windows
      arch: x86
notifications:
  email: false
after_success:
  - |
    julia -e '
      VERSION >= v"0.7.0-DEV.3656" && using Pkg
      VERSION >= v"0.7.0-DEV.5183" || cd(Pkg.dir("FTPClient"))
      Pkg.add("Coverage"); using Coverage
      Codecov.submit(process_folder())'
