language: julia
os:
  - osx
  - linux
  - windows
arch:
  - x64
  - x86
julia:
  - 1.0  # Latest LTS release
  - 1    # Latest stable release
  - nightly
env:
  - PYTHON=""  # For use with the FTPServer.jl test dependency
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly

  # Test 32-bit only on Linux
  exclude:
    - os: osx
      arch: x86
    - os: windows
      arch: x86
notifications:
  email:
    recipients:
      - nightly-dev@invenia.ca
    on_success: never
    on_failure: always
    if: type = cron
after_success:
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage"); using Coverage
      Codecov.submit(process_folder())'
