language: julia
os:
  - osx
  - linux
julia:
  - 0.4
  - 0.5
  - 0.6
  - nightly
notifications:
  email: false
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia -e 'Pkg.clone(pwd()); Pkg.build("FTPClient"); Pkg.test("FTPClient"; coverage=true)'
after_success:
 - julia -e 'cd(Pkg.dir("FTPClient")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
